/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.co.indocyber.view;

import id.co.model.Category;
import id.co.model.WordModel;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class GuessingGame extends javax.swing.JFrame {
WordModel modelWorld;

/**
     * Creates new form GuessingGame
     */
    

    public GuessingGame() throws IOException {
        initComponents();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSoal = new javax.swing.JTextField();
        txtJawaban = new javax.swing.JTextField();
        btnCheckAnswer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblJawaban = new javax.swing.JLabel();
        btnMulai = new javax.swing.JButton();
        btnHint = new javax.swing.JButton();
        lblHint = new javax.swing.JLabel();
        cmbKategory = new javax.swing.JComboBox<String>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtSoal.setEditable(false);
        txtSoal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnCheckAnswer.setText("Periksa");
        btnCheckAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckAnswerActionPerformed(evt);
            }
        });

        jLabel1.setText("Jawaban :");

        lblJawaban.setText("Belum Ada Jawaban");

        btnMulai.setText("Mulai");
        btnMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulaiActionPerformed(evt);
            }
        });

        btnHint.setText("Bantu Dong");
        btnHint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHintActionPerformed(evt);
            }
        });

        cmbKategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hewan", "Makanan" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMulai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmbKategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(btnHint)
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSoal, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtJawaban, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnCheckAnswer, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblJawaban, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(lblHint, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMulai)
                    .addComponent(btnHint)
                    .addComponent(cmbKategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblHint, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(txtSoal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(txtJawaban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCheckAnswer)
                .addGap(37, 37, 37)
                .addComponent(lblJawaban, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulaiActionPerformed
        int kategori = 0; 
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("SwingGuessWordSpringPU");
        EntityManager em = emf.createEntityManager();
        if(cmbKategory.getSelectedItem().equals("Hewan")){
            kategori = 1;
        } else if(cmbKategory.getSelectedItem().equals("Makanan")){
            kategori = 2;
        }
        
        Category wm = em.find(Category.class, kategori);
        List<WordModel> wordModels = wm.getWordModels();
        for (WordModel wordModel : wordModels) {
            System.out.println(wordModel.getBasicWord());
        }
        
            
        em.close();
        emf.close();

        int soalIndex = (int) Math.floor(Math.random() * wordModels.size());
        modelWorld = wordModels.get(soalIndex);
        txtSoal.setText(modelWorld.acakHuruf());

    }//GEN-LAST:event_btnMulaiActionPerformed

    private void btnCheckAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckAnswerActionPerformed
        try {
            //String jawaban = txtJawaban.getText().trim();
            int i = 0;
            modelWorld.setJawaban(txtJawaban.getText().trim());
            if (modelWorld.cekJawaban()) {
                lblJawaban.setText("Jenius ");
                lblHint.setText("");
            } else {
                lblJawaban.setText("Dumb");
                i++;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Tekan Tombol Mulai");
        }
    }//GEN-LAST:event_btnCheckAnswerActionPerformed

    private void btnHintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHintActionPerformed
        try {
            lblHint.setText(modelWorld.getHint());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Klik Tombol Mulai");
        }
    }//GEN-LAST:event_btnHintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {               
                try {
                    new GuessingGame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(GuessingGame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckAnswer;
    private javax.swing.JButton btnHint;
    private javax.swing.JButton btnMulai;
    private javax.swing.JComboBox<String> cmbKategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblHint;
    private javax.swing.JLabel lblJawaban;
    private javax.swing.JTextField txtJawaban;
    private javax.swing.JTextField txtSoal;
    // End of variables declaration//GEN-END:variables
}
